export const RESERVATION_PENDING = '@@grabfood/RESERVATION_PENDING';
export const RESERVATION_FULFILLED = '@@grabfood/RESERVATION_FULFILLED';
export const RESERVATION_REJECTED = '@@grabfood/RESERVATION_REJECTED';
export const RESERVATION_SHOW_TOASTER = '@@grabfood/RESERVATION_SHOW_TOASTER';
export const RESERVATION_HIDE_TOASTER = '@@grabfood/RESERVATION_HIDE_TOASTER';
