export const FAVORITE_FOOD_PENDING = '@@grabfood/FAVORITE_FOOD_PENDING';
export const FAVORITE_FOOD_FULFILLED = '@@grabfood/FAVORITE_FOOD_FULFILLED';
export const FAVORITE_FOOD_REJECTED = '@@grabfood/FAVORITE_FOOD_REJECTED';
