export const RESTAURANT_PENDING = '@@grabfood/RESTAURANT_PENDING';
export const RESTAURANT_FULFILLED = '@@grabfood/RESTAURANT_FULFILLED';
export const RESTAURANT_REJECTED = '@@grabfood/RESTAURANT_REJECTED';

export const RESERVATION_PENDING = '@@grabfood/RESERVATION_PENDING';
export const RESERVATION_FULFILLED = '@@grabfood/RESERVATION_FULFILLED';
export const RESERVATION_REJECTED = '@@grabfood/RESERVATION_REJECTED';
