export const RESTAURANT_PENDING = '@@grabfood/RESTAURANT_PENDING';
export const RESTAURANT_FULFILLED = '@@grabfood/RESTAURANT_FULFILLED';
export const RESTAURANT_REJECTED = '@@grabfood/RESTAURANT_REJECTED';
